#!/bin/zsh
#
# Converts position.kml <name>12/05/21 02:17</name> to <name>2021-05-12 02:17</name>

proc_dir=$MERMAID/processed_everyone
for mer_dir in $( ls -1d $proc_dir/*/ ); do
    in=$mer_dir/position.kml
    out=$mer_dir/position_isodate.kml
    if [[ -f $in ]]; then
	sed -E 's@<name>([0-9]{2})/([0-9]{2})/([0-9]{2}) ([0-9]{2}:[0-9]{2})</name>@<name>20\3-\2-\1 \4</name>@g' $in > $out
	printf "Wrote %s\n" $out
    else
	printf "Skipped (file does not exist): %s\n" $in
    fi
done
