#! /bin/zsh
# usage: version_diffs [COMMIT] [VERSION]
#
# ex: version_diffs abdc12345 v2.1

COMMIT=$1
VERSION=$2

for pyfile in $AUTOMAID/scripts/*py; do
    git diff $COMMIT -- $pyfile > $(basename $pyfile)_$VERSION.diff
done
